return {

    -- The amount of seconds it takes for you to stand AFK and get kicked
    timeUntilAFKKick = 1000,

    -- The groups to ignore when checking for AFK activity
    ignoreGroupsForAFK = {
        'group.mod',
        'group.admin',
    },

    blacklisted = {
        vehicles = {
            `SHAMAL`,
            `LUXOR`,
            `LUXOR2`,
            `JET`,
            `LAZER`,
            `BUZZARD`,
            `BUZZARD2`,
            `ANNIHILATOR`,
            `SAVAGE`,
            `TITAN`,
            `RHINO`,
            `FIRETRUK`,
            `MULE`,
            `MAVERICK`,
            `BLIMP`,
            `AIRTUG`,
            `CAMPER`,
            `HYDRA`,
            `OPPRESSOR`,
            `technical3`,
            `insurgent3`,
            `apc`,
            `tampa3`,
            `trailersmall2`,
            `halftrack`,
            `hunter`,
            `vigilante`,
            `akula`,
            `barrage`,
            `khanjali`,
            `caracara`,
            `blimp3`,
            `menacer`,
            `oppressor2`,
            `scramjet`,
            `strikeforce`,
            `cerberus`,
            `cerberus2`,
            `cerberus3`,
            `scarab`,
            `scarab2`,
            `scarab3`,
            `rrocket`,
            `ruiner2`,
            `deluxo`,
        },

        peds = {
            `s_m_y_ranger_01`,
            `s_m_y_sheriff_01`,
            `s_m_y_cop_01`,
            `s_f_y_sheriff_01`,
            `s_f_y_cop_01`,
            `s_m_y_hwaycop_01`,
        },
    }
}